name: build

on: [ push, pull_request ]

env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

jobs:
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.4', '8.0' ]

    steps:
      - name: Install sendmail
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install sendmail

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          rm -rf vendor/
          rm -f composer.lock
          composer self-update -vvv
          composer install $DEFAULT_COMPOSER_FLAGS

      - name: PHPUnit
        run: vendor/bin/phpunit --verbose --colors=always
